Fundamentos de probabilidad -- NumPy y StatsModels
===

**Juan David Velásquez Henao**  
jdvelasq@unal.edu.co   
Universidad Nacional de Colombia, Sede Medellín  
Facultad de Minas  
Medellín, Colombia

---

Haga click [aquí](https://github.com/jdvelasq/series-de-tiempo/blob/master/04-Ipy-probabilidad.ipynb) para acceder a la última versión online

Haga click [aquí](http://nbviewer.jupyter.org/github/jdvelasq/series-de-tiempo/blob/master/04-Ipy-probabilidad.ipynb) para ver la última versión online en `nbviewer`. 

---

# Generación de secuencias aleatorias con la Python Standard Library

> [random.py](https://docs.python.org/3/library/random.html) at The Standard Python Library  

La librería `random.py` contiene funciones para generación de diferentes secuencias aleatorias. 

In [1]:
import random

## Generación de números aleatorios en punto flotante 

In [49]:
# random.random()
#   número aleatorio entre [0.0, 1.0)
random.random()

0.6839339568770466

In [57]:
# para generar una secuencia de aleatorios se usa una list comprenhension
[random.random() for n in range(4)]

[0.6572364087765133,
 0.4693323901942733,
 0.49167426785761004,
 0.4775592845096345]

In [50]:
# random.uniform(a, b)¶
#   genera un aleatorio N tal que a <= N <= b
random.uniform(1, 2)

1.6311119555926594

In [51]:
# random.triangular(low, high, mode)
#   número aleatorio triangular
random.triangular(0,2,1)

0.5661472279430578

In [53]:
# random.gauss(mu, sigma)
#   número aleatorio normal (mu, sigma)
random.gauss(0, 1)

0.4078789804165166

Otros generadores de números aleatorios:
* `random.betavariate(alpha, beta)`
* `random.expovariate(lambd)`
* `random.gammavariate(alpha, beta)`
* `random.lognormvariate(mu, sigma)`
* `random.normalvariate(mu, sigma)`
* `random.paretovariate(alpha)`
* `random.weibullvariate(alpha, beta)`

## Generación de números aleatorios enteros

In [2]:
# random.randint(a, b) genera un entero aleatorio N entre a <= N <= b
random.randint(1,5)

3

In [26]:
# genera un entero aleatorio (base 10) entre los 
# enteros de dos bits {00 = 0, 01 = 1, 10 = 2, 11 = 3}
random.getrandbits(2) 

3

In [28]:
# random.randrange(stop)
# random.randrange(start, stop[, step])
#   retorna un entero de la secuencia especificada
random.randrange(5)

2

In [38]:
random.randrange(1,5,2) # {1, 3}

3

In [54]:
# random.choice(seq)  
# retorna un elemento de la secuencia seq
random.choice([1, 2, 3, 4])

4

## Permutaciones y muestreo

In [46]:
# random.shuffle(x[, random])
#   mezcla la secuencia x usando el generador de aleatorios random
#   note que la función no devuelve nada
x = [1, 2, 3, 4]
random.shuffle(x)
x

[4, 3, 2, 1]

In [48]:
# random.sample(population, k)
#   obtiene una muestra de k elementos de la población
random.sample(range(1,10), 3)

[9, 3, 4]

## Semilla

In [58]:
# inicializa el generador aleatorio (genera la misma secuencia)
random.seed(18)
[random.randint(1, 5) for n in range(4)]

[2, 1, 4, 3]

In [59]:
random.seed(18)
[random.randint(1, 5) for n in range(4)]

[2, 1, 4, 3]

In [60]:
x = random.getstate()  # guarda el estado interno del generador.
[random.randint(1, 5) for n in range(4)]   # permite generar una secuencia desde un punto determinado

[2, 2, 4, 4]

In [61]:
random.setstate(x)     # restaura el estado interno del generador.
[random.randint(1, 5) for n in range(4)]   # genera el mismo aleatorio anterior

[2, 2, 4, 4]

# Generación de secuencias aleatorias con NumPy

> [`numpy.random`](http://docs.scipy.org/doc/numpy/reference/routines.random.html) at SciPy.org

In [67]:
import numpy as np

## Números aleatorios en punto flotante

In [83]:
# `sample([size])` -- aleatorios flotantes en el rango [0.0, 1.0).
np.random.random([2, 3])

array([[ 0.4965064 ,  0.23383735,  0.78379117],
       [ 0.41206911,  0.80123168,  0.27492485]])

In [80]:
# `random_sample([size])` -- aleatorios flotantes en el rango [0.0, 1.0).
np.random.random_sample([2, 3])

array([[ 0.25687175,  0.36872676,  0.00184624],
       [ 0.16590004,  0.23109507,  0.18527201]])

In [81]:
# `random([size])` -- aleatorios flotantes en el rango [0.0, 1.0).
np.random.random([2, 3])

array([[ 0.37902673,  0.10206039,  0.38269618],
       [ 0.09428272,  0.65335276,  0.20024315]])

In [82]:
# `ranf([size])` -- aleatorios flotantes en el rango [0.0, 1.0).
np.random.ranf([2, 3])

array([[ 0.36295642,  0.95964096,  0.9290549 ],
       [ 0.65519902,  0.90384487,  0.78276551]])

In [86]:
# `choice(a[, size, replace, p])` -- Muestra aleatoria 1D
np.random.choice(range(10), # población
                5,          # tamaño
                True)       # reemplazo

array([4, 5, 2, 1, 9])

In [85]:
np.random.choice(range(10), # población
                5,          # tamaño
                False)      # reemplazo

array([5, 7, 4, 6, 3])

In [76]:
# `rand(d0, d1, ..., dn)` -- retorna una muestra de aleatorios uniformes.
np.random.rand(2, 

array([[ 0.31246059,  0.60225495,  0.8730785 ],
       [ 0.20510907,  0.21015151,  0.21203842]])

In [77]:
# `randn(d0, d1, ..., dn)` -- retorna una muestra de una distribución normal estándar.
np.random.randn(2, 3)

array([[ 0.27577277,  0.25735575,  0.74229743],
       [-0.16057308,  0.80653699, -0.4123505 ]])

In [74]:
np.random.randint(2,      # limite inferior
                  8,      # limite superior
                  [5, 3]) # tamaño

array([[4, 7, 3],
       [6, 2, 5],
       [7, 5, 6],
       [2, 6, 4],
       [2, 7, 5]])

In [96]:
# `bytes(length)`
np.random.bytes(2)

b'\xe6\xf6'

En la página web de SciPy.org aparecen listadas todas las funciones generadoras de aleatorios para distintos tipos de distribución.

## Permutaciones

In [90]:
# shuffle(x) -- mezcla la secuencia x 
x = [1, 2, 3, 4, 5]
np.random.shuffle(x)
x

[3, 2, 1, 4, 5]

In [91]:
# permutation(x) -- permuta la secuencia
np.random.permutation([1, 2, 3, 4, 5])

array([1, 3, 4, 5, 2])

## Semilla

In [92]:
# seed([seed]) -- Semilla del generador.
np.random.seed(123)
np.random.random()

0.6964691855978616

In [93]:
np.random.seed(123)
np.random.random()

0.6964691855978616

In [94]:
# get_state() -- retorna el estado del generador.
# set_state(state) -- establece el estado del generador.
x = np.random.get_state()
np.random.random()
np.random.random()

0.2268514535642031

In [95]:
np.random.set_state(x)
np.random.random()
np.random.random()

0.2268514535642031

**Ejercicio.--** Implemente la función bootstrap en Python, la cual permite realizar bootstrap no paramétrico.

**Ejercicio.--** Construya una interfaz gráfica de análisis de distribuciones de probabilidad usando Python y una de las librerías disponibles para interfaces de usuario como `pyforms`.

Fundamentos de probabilidad -- NumPy y StatsModels
===

**Juan David Velásquez Henao**  
jdvelasq@unal.edu.co   
Universidad Nacional de Colombia, Sede Medellín  
Facultad de Minas  
Medellín, Colombia

---

Haga click [aquí](https://github.com/jdvelasq/series-de-tiempo/blob/master/04-Ipy-probabilidad.ipynb) para acceder a la última versión online

Haga click [aquí](http://nbviewer.jupyter.org/github/jdvelasq/series-de-tiempo/blob/master/04-Ipy-probabilidad.ipynb) para ver la última versión online en `nbviewer`. 

---